//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.Future.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Micro.Future.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 是否活跃 的本地化字符串。
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加板块 的本地化字符串。
        /// </summary>
        internal static string AddWindow {
            get {
                return ResourceManager.GetString("AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有持仓 的本地化字符串。
        /// </summary>
        internal static string All_Position {
            get {
                return ResourceManager.GetString("All_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有委托单 的本地化字符串。
        /// </summary>
        internal static string AllExecution {
            get {
                return ResourceManager.GetString("AllExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有成交 的本地化字符串。
        /// </summary>
        internal static string AllTraded {
            get {
                return ResourceManager.GetString("AllTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卖价 的本地化字符串。
        /// </summary>
        internal static string AskPrice {
            get {
                return ResourceManager.GetString("AskPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卖量 的本地化字符串。
        /// </summary>
        internal static string AskSize {
            get {
                return ResourceManager.GetString("AskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 买价 的本地化字符串。
        /// </summary>
        internal static string BidPrice {
            get {
                return ResourceManager.GetString("BidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 买量 的本地化字符串。
        /// </summary>
        internal static string BidSize {
            get {
                return ResourceManager.GetString("BidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期货公司代码 的本地化字符串。
        /// </summary>
        internal static string BrokerID {
            get {
                return ResourceManager.GetString("BrokerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 买入 的本地化字符串。
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订单 的本地化字符串。
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销时间 的本地化字符串。
        /// </summary>
        internal static string CancelTime {
            get {
                return ResourceManager.GetString("CancelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中金期货 的本地化字符串。
        /// </summary>
        internal static string CFFEX {
            get {
                return ResourceManager.GetString("CFFEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓金额 的本地化字符串。
        /// </summary>
        internal static string CloseAmount {
            get {
                return ResourceManager.GetString("CloseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓盈亏 的本地化字符串。
        /// </summary>
        internal static string CloseProfit {
            get {
                return ResourceManager.GetString("CloseProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平今 的本地化字符串。
        /// </summary>
        internal static string CloseToday {
            get {
                return ResourceManager.GetString("CloseToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓量 的本地化字符串。
        /// </summary>
        internal static string CloseVolume {
            get {
                return ResourceManager.GetString("CloseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列设置 的本地化字符串。
        /// </summary>
        internal static string ColumnSettings {
            get {
                return ResourceManager.GetString("ColumnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手续费 的本地化字符串。
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人信息 的本地化字符串。
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合约 的本地化字符串。
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郑州期货 的本地化字符串。
        /// </summary>
        internal static string CZCE {
            get {
                return ResourceManager.GetString("CZCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大连期货 的本地化字符串。
        /// </summary>
        internal static string DCE {
            get {
                return ResourceManager.GetString("DCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除报价 的本地化字符串。
        /// </summary>
        internal static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 买卖 的本地化字符串。
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易所 的本地化字符串。
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行类型 的本地化字符串。
        /// </summary>
        internal static string ExecType {
            get {
                return ResourceManager.GetString("ExecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单明细 的本地化字符串。
        /// </summary>
        internal static string ExecutionDetail {
            get {
                return ResourceManager.GetString("ExecutionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 委托单板块 的本地化字符串。
        /// </summary>
        internal static string ExecutionWindow {
            get {
                return ResourceManager.GetString("ExecutionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速下单 的本地化字符串。
        /// </summary>
        internal static string FastOrder {
            get {
                return ResourceManager.GetString("FastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选配置 的本地化字符串。
        /// </summary>
        internal static string FilterSettings {
            get {
                return ResourceManager.GetString("FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能区 的本地化字符串。
        /// </summary>
        internal static string FunctionArea {
            get {
                return ResourceManager.GetString("FunctionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资金 的本地化字符串。
        /// </summary>
        internal static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日有效 的本地化字符串。
        /// </summary>
        internal static string GFD {
            get {
                return ResourceManager.GetString("GFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直到取消 的本地化字符串。
        /// </summary>
        internal static string GTC {
            get {
                return ResourceManager.GetString("GTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投保 的本地化字符串。
        /// </summary>
        internal static string HedgeFlag {
            get {
                return ResourceManager.GetString("HedgeFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂单时间 的本地化字符串。
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保单价格 的本地化字符串。
        /// </summary>
        internal static string LimitPrice {
            get {
                return ResourceManager.GetString("LimitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        internal static string Login_Server {
            get {
                return ResourceManager.GetString("Login_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多头冻结 的本地化字符串。
        /// </summary>
        internal static string LongFrozen {
            get {
                return ResourceManager.GetString("LongFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多头金额 的本地化字符串。
        /// </summary>
        internal static string LongFrozenAmount {
            get {
                return ResourceManager.GetString("LongFrozenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交价 的本地化字符串。
        /// </summary>
        internal static string MatchPrice {
            get {
                return ResourceManager.GetString("MatchPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态信息 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开平 的本地化字符串。
        /// </summary>
        internal static string OffsetFlag {
            get {
                return ResourceManager.GetString("OffsetFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓金额 的本地化字符串。
        /// </summary>
        internal static string OpenAmount {
            get {
                return ResourceManager.GetString("OpenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开平 的本地化字符串。
        /// </summary>
        internal static string OpenClose {
            get {
                return ResourceManager.GetString("OpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓成本 的本地化字符串。
        /// </summary>
        internal static string OpenCost {
            get {
                return ResourceManager.GetString("OpenCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前挂单 的本地化字符串。
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓量 的本地化字符串。
        /// </summary>
        internal static string OpenVolume {
            get {
                return ResourceManager.GetString("OpenVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自选合约 的本地化字符串。
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下单 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单编号 的本地化字符串。
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报单编号 的本地化字符串。
        /// </summary>
        internal static string OrderSysID {
            get {
                return ResourceManager.GetString("OrderSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量 的本地化字符串。
        /// </summary>
        internal static string OrderVolume {
            get {
                return ResourceManager.GetString("OrderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持仓 的本地化字符串。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持仓成本 的本地化字符串。
        /// </summary>
        internal static string PositionCost {
            get {
                return ResourceManager.GetString("PositionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多空 的本地化字符串。
        /// </summary>
        internal static string PositionDirection {
            get {
                return ResourceManager.GetString("PositionDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持仓盈亏 的本地化字符串。
        /// </summary>
        internal static string PositionProfit {
            get {
                return ResourceManager.GetString("PositionProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持仓板块 的本地化字符串。
        /// </summary>
        internal static string PositionWindow {
            get {
                return ResourceManager.GetString("PositionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行情 的本地化字符串。
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交量 的本地化字符串。
        /// </summary>
        internal static string QuoteVolume {
            get {
                return ResourceManager.GetString("QuoteVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报价表 的本地化字符串。
        /// </summary>
        internal static string QuoteWindow {
            get {
                return ResourceManager.GetString("QuoteWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卖出 的本地化字符串。
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器已连接 的本地化字符串。
        /// </summary>
        internal static string Server_Connected {
            get {
                return ResourceManager.GetString("Server_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器未连接 的本地化字符串。
        /// </summary>
        internal static string Server_Unconnected {
            get {
                return ResourceManager.GetString("Server_Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海期货 的本地化字符串。
        /// </summary>
        internal static string SHFE {
            get {
                return ResourceManager.GetString("SHFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空头冻结 的本地化字符串。
        /// </summary>
        internal static string ShortFrozen {
            get {
                return ResourceManager.GetString("ShortFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空头金额 的本地化字符串。
        /// </summary>
        internal static string ShortFrozenAmount {
            get {
                return ResourceManager.GetString("ShortFrozenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期类型 的本地化字符串。
        /// </summary>
        internal static string TIF {
            get {
                return ResourceManager.GetString("TIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        internal static string TimeCondition {
            get {
                return ResourceManager.GetString("TimeCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日持仓 的本地化字符串。
        /// </summary>
        internal static string TodayPosition {
            get {
                return ResourceManager.GetString("TodayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成交 的本地化字符串。
        /// </summary>
        internal static string Traded {
            get {
                return ResourceManager.GetString("Traded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓记录 的本地化字符串。
        /// </summary>
        internal static string Traded_Close {
            get {
                return ResourceManager.GetString("Traded_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓记录 的本地化字符串。
        /// </summary>
        internal static string Traded_Open {
            get {
                return ResourceManager.GetString("Traded_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交日期 的本地化字符串。
        /// </summary>
        internal static string TradeDate {
            get {
                return ResourceManager.GetString("TradeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交明细 的本地化字符串。
        /// </summary>
        internal static string TradeDetail {
            get {
                return ResourceManager.GetString("TradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交板块 的本地化字符串。
        /// </summary>
        internal static string TradedWindow {
            get {
                return ResourceManager.GetString("TradedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交编号 的本地化字符串。
        /// </summary>
        internal static string TradeID {
            get {
                return ResourceManager.GetString("TradeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交价格 的本地化字符串。
        /// </summary>
        internal static string TradePrice {
            get {
                return ResourceManager.GetString("TradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交时间 的本地化字符串。
        /// </summary>
        internal static string TradeTime {
            get {
                return ResourceManager.GetString("TradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交量 的本地化字符串。
        /// </summary>
        internal static string TradeVolume {
            get {
                return ResourceManager.GetString("TradeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易类型 的本地化字符串。
        /// </summary>
        internal static string TradingType {
            get {
                return ResourceManager.GetString("TradingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品种类 的本地化字符串。
        /// </summary>
        internal static string Underlying {
            get {
                return ResourceManager.GetString("Underlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后修改时间 的本地化字符串。
        /// </summary>
        internal static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 占用保证金 的本地化字符串。
        /// </summary>
        internal static string UseMargin {
            get {
                return ResourceManager.GetString("UseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        internal static string UserClient {
            get {
                return ResourceManager.GetString("UserClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报单数量 的本地化字符串。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未成交数量 的本地化字符串。
        /// </summary>
        internal static string VolumeRemain {
            get {
                return ResourceManager.GetString("VolumeRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成交数量 的本地化字符串。
        /// </summary>
        internal static string VolumeTraded {
            get {
                return ResourceManager.GetString("VolumeTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 板块标题 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨日持仓 的本地化字符串。
        /// </summary>
        internal static string YdPosition {
            get {
                return ResourceManager.GetString("YdPosition", resourceCulture);
            }
        }
    }
}
