//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.Future.Business.Handler.Enums {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Micro.Future.Business.Handler.Enums.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 买 的本地化字符串。
        /// </summary>
        internal static string DirectionType_Buy {
            get {
                return ResourceManager.GetString("DirectionType_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 净头寸 的本地化字符串。
        /// </summary>
        internal static string DirectionType_NET {
            get {
                return ResourceManager.GetString("DirectionType_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卖 的本地化字符串。
        /// </summary>
        internal static string DirectionType_Sell {
            get {
                return ResourceManager.GetString("DirectionType_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限价单 的本地化字符串。
        /// </summary>
        internal static string EXECTYPE_LIMIT {
            get {
                return ResourceManager.GetString("EXECTYPE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场单 的本地化字符串。
        /// </summary>
        internal static string EXECTYPE_MARKET {
            get {
                return ResourceManager.GetString("EXECTYPE_MARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套利 的本地化字符串。
        /// </summary>
        internal static string HEDGETYPE_ARBITRAGE {
            get {
                return ResourceManager.GetString("HEDGETYPE_ARBITRAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套保 的本地化字符串。
        /// </summary>
        internal static string HEDGETYPE_HEDGE {
            get {
                return ResourceManager.GetString("HEDGETYPE_HEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投机 的本地化字符串。
        /// </summary>
        internal static string HEDGETYPE_SPECULATION {
            get {
                return ResourceManager.GetString("HEDGETYPE_SPECULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平仓 的本地化字符串。
        /// </summary>
        internal static string OpenClose_CLOSE {
            get {
                return ResourceManager.GetString("OpenClose_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平今 的本地化字符串。
        /// </summary>
        internal static string OpenClose_CLOSETODAY {
            get {
                return ResourceManager.GetString("OpenClose_CLOSETODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平昨 的本地化字符串。
        /// </summary>
        internal static string OpenClose_CLOSEYESTERDAY {
            get {
                return ResourceManager.GetString("OpenClose_CLOSEYESTERDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强平 的本地化字符串。
        /// </summary>
        internal static string OpenClose_FORCECLOSE {
            get {
                return ResourceManager.GetString("OpenClose_FORCECLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强减 的本地化字符串。
        /// </summary>
        internal static string OpenClose_FORCEOFF {
            get {
                return ResourceManager.GetString("OpenClose_FORCEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地强平 的本地化字符串。
        /// </summary>
        internal static string OpenClose_LOCALFORCECLOSE {
            get {
                return ResourceManager.GetString("OpenClose_LOCALFORCECLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓 的本地化字符串。
        /// </summary>
        internal static string OpenClose_OPEN {
            get {
                return ResourceManager.GetString("OpenClose_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部成交 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_ALL_TRADED {
            get {
                return ResourceManager.GetString("OrderStatus_ALL_TRADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤单失败 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_CANCEL_REJECTED {
            get {
                return ResourceManager.GetString("OrderStatus_CANCEL_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已撤单 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_CANCELED {
            get {
                return ResourceManager.GetString("OrderStatus_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤单中 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_CANCELING {
            get {
                return ResourceManager.GetString("OrderStatus_CANCELING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开仓被拒绝 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_OPEN_REJECTED {
            get {
                return ResourceManager.GetString("OrderStatus_OPEN_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已提交 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_OPENNING {
            get {
                return ResourceManager.GetString("OrderStatus_OPENNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分成交 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_PARTIAL_TRADED {
            get {
                return ResourceManager.GetString("OrderStatus_PARTIAL_TRADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分提交中 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_PARTIAL_TRADING {
            get {
                return ResourceManager.GetString("OrderStatus_PARTIAL_TRADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_REJECTED {
            get {
                return ResourceManager.GetString("OrderStatus_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_UNDEFINED {
            get {
                return ResourceManager.GetString("OrderStatus_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当日有效 的本地化字符串。
        /// </summary>
        internal static string OrderTIFType_GFD {
            get {
                return ResourceManager.GetString("OrderTIFType_GFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即完成或撤单 的本地化字符串。
        /// </summary>
        internal static string OrderTIFType_IOC {
            get {
                return ResourceManager.GetString("OrderTIFType_IOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多 的本地化字符串。
        /// </summary>
        internal static string PositionDirectionType_LONG {
            get {
                return ResourceManager.GetString("PositionDirectionType_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空 的本地化字符串。
        /// </summary>
        internal static string PositionDirectionType_SHORT {
            get {
                return ResourceManager.GetString("PositionDirectionType_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string TRADINGTYPE_AUTO {
            get {
                return ResourceManager.GetString("TRADINGTYPE_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套利 的本地化字符串。
        /// </summary>
        internal static string TRADINGTYPE_HEDGE {
            get {
                return ResourceManager.GetString("TRADINGTYPE_HEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动 的本地化字符串。
        /// </summary>
        internal static string TRADINGTYPE_MANUAL {
            get {
                return ResourceManager.GetString("TRADINGTYPE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行情 的本地化字符串。
        /// </summary>
        internal static string TRADINGTYPE_QUOTE {
            get {
                return ResourceManager.GetString("TRADINGTYPE_QUOTE", resourceCulture);
            }
        }
    }
}
