//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.Future.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Micro.Future.ResourcesLanguage.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddWindow 的本地化字符串。
        /// </summary>
        internal static string AddWindow {
            get {
                return ResourceManager.GetString("AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Position 的本地化字符串。
        /// </summary>
        internal static string All_Position {
            get {
                return ResourceManager.GetString("All_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllExecution 的本地化字符串。
        /// </summary>
        internal static string AllExecution {
            get {
                return ResourceManager.GetString("AllExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllTraded 的本地化字符串。
        /// </summary>
        internal static string AllTraded {
            get {
                return ResourceManager.GetString("AllTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AskPrice 的本地化字符串。
        /// </summary>
        internal static string AskPrice {
            get {
                return ResourceManager.GetString("AskPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AskSize 的本地化字符串。
        /// </summary>
        internal static string AskSize {
            get {
                return ResourceManager.GetString("AskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BidPrice 的本地化字符串。
        /// </summary>
        internal static string BidPrice {
            get {
                return ResourceManager.GetString("BidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BidSize 的本地化字符串。
        /// </summary>
        internal static string BidSize {
            get {
                return ResourceManager.GetString("BidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BrokerID 的本地化字符串。
        /// </summary>
        internal static string BrokerID {
            get {
                return ResourceManager.GetString("BrokerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CancelOrder 的本地化字符串。
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CancelTime 的本地化字符串。
        /// </summary>
        internal static string CancelTime {
            get {
                return ResourceManager.GetString("CancelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CFFEX 的本地化字符串。
        /// </summary>
        internal static string CFFEX {
            get {
                return ResourceManager.GetString("CFFEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloseAmount 的本地化字符串。
        /// </summary>
        internal static string CloseAmount {
            get {
                return ResourceManager.GetString("CloseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloseProfit 的本地化字符串。
        /// </summary>
        internal static string CloseProfit {
            get {
                return ResourceManager.GetString("CloseProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloseVolume 的本地化字符串。
        /// </summary>
        internal static string CloseVolume {
            get {
                return ResourceManager.GetString("CloseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColumnSettings 的本地化字符串。
        /// </summary>
        internal static string ColumnSettings {
            get {
                return ResourceManager.GetString("ColumnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commission 的本地化字符串。
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContactInfo 的本地化字符串。
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract 的本地化字符串。
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CZCE 的本地化字符串。
        /// </summary>
        internal static string CZCE {
            get {
                return ResourceManager.GetString("CZCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DCE 的本地化字符串。
        /// </summary>
        internal static string DCE {
            get {
                return ResourceManager.GetString("DCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteOrder 的本地化字符串。
        /// </summary>
        internal static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange 的本地化字符串。
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutionType 的本地化字符串。
        /// </summary>
        internal static string ExecType {
            get {
                return ResourceManager.GetString("ExecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutionDetail 的本地化字符串。
        /// </summary>
        internal static string ExecutionDetail {
            get {
                return ResourceManager.GetString("ExecutionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutionWindow 的本地化字符串。
        /// </summary>
        internal static string ExecutionWindow {
            get {
                return ResourceManager.GetString("ExecutionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FastOrder 的本地化字符串。
        /// </summary>
        internal static string FastOrder {
            get {
                return ResourceManager.GetString("FastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FilterSettings 的本地化字符串。
        /// </summary>
        internal static string FilterSettings {
            get {
                return ResourceManager.GetString("FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FunctionArea 的本地化字符串。
        /// </summary>
        internal static string FunctionArea {
            get {
                return ResourceManager.GetString("FunctionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fund 的本地化字符串。
        /// </summary>
        internal static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HedgeFlag 的本地化字符串。
        /// </summary>
        internal static string HedgeFlag {
            get {
                return ResourceManager.GetString("HedgeFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InsertTime 的本地化字符串。
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LimitPrice 的本地化字符串。
        /// </summary>
        internal static string LimitPrice {
            get {
                return ResourceManager.GetString("LimitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogIn 的本地化字符串。
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string Login_Server {
            get {
                return ResourceManager.GetString("Login_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LongFrozen 的本地化字符串。
        /// </summary>
        internal static string LongFrozen {
            get {
                return ResourceManager.GetString("LongFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LongFrozenAmount 的本地化字符串。
        /// </summary>
        internal static string LongFrozenAmount {
            get {
                return ResourceManager.GetString("LongFrozenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MatchPrice 的本地化字符串。
        /// </summary>
        internal static string MatchPrice {
            get {
                return ResourceManager.GetString("MatchPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OffsetFlag 的本地化字符串。
        /// </summary>
        internal static string OffsetFlag {
            get {
                return ResourceManager.GetString("OffsetFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenAmount 的本地化字符串。
        /// </summary>
        internal static string OpenAmount {
            get {
                return ResourceManager.GetString("OpenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenClose 的本地化字符串。
        /// </summary>
        internal static string OpenClose {
            get {
                return ResourceManager.GetString("OpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenCost 的本地化字符串。
        /// </summary>
        internal static string OpenCost {
            get {
                return ResourceManager.GetString("OpenCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening 的本地化字符串。
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenVolume 的本地化字符串。
        /// </summary>
        internal static string OpenVolume {
            get {
                return ResourceManager.GetString("OpenVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional 的本地化字符串。
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderID 的本地化字符串。
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderSysID 的本地化字符串。
        /// </summary>
        internal static string OrderSysID {
            get {
                return ResourceManager.GetString("OrderSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PassWord 的本地化字符串。
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost 的本地化字符串。
        /// </summary>
        internal static string PositionCost {
            get {
                return ResourceManager.GetString("PositionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        internal static string PositionDirection {
            get {
                return ResourceManager.GetString("PositionDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Porfit 的本地化字符串。
        /// </summary>
        internal static string PositionProfit {
            get {
                return ResourceManager.GetString("PositionProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PositionWindow 的本地化字符串。
        /// </summary>
        internal static string PositionWindow {
            get {
                return ResourceManager.GetString("PositionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quote 的本地化字符串。
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        internal static string QuoteVolume {
            get {
                return ResourceManager.GetString("QuoteVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuoteWindow 的本地化字符串。
        /// </summary>
        internal static string QuoteWindow {
            get {
                return ResourceManager.GetString("QuoteWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Connected 的本地化字符串。
        /// </summary>
        internal static string Server_Connected {
            get {
                return ResourceManager.GetString("Server_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Unconnected 的本地化字符串。
        /// </summary>
        internal static string Server_Unconnected {
            get {
                return ResourceManager.GetString("Server_Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHFE 的本地化字符串。
        /// </summary>
        internal static string SHFE {
            get {
                return ResourceManager.GetString("SHFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortFrozen 的本地化字符串。
        /// </summary>
        internal static string ShortFrozen {
            get {
                return ResourceManager.GetString("ShortFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortFrozenAmount 的本地化字符串。
        /// </summary>
        internal static string ShortFrozenAmount {
            get {
                return ResourceManager.GetString("ShortFrozenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIF 的本地化字符串。
        /// </summary>
        internal static string TIF {
            get {
                return ResourceManager.GetString("TIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TitleText 的本地化字符串。
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TodayPosition 的本地化字符串。
        /// </summary>
        internal static string TodayPosition {
            get {
                return ResourceManager.GetString("TodayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traded 的本地化字符串。
        /// </summary>
        internal static string Traded {
            get {
                return ResourceManager.GetString("Traded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traded Close 的本地化字符串。
        /// </summary>
        internal static string Traded_Close {
            get {
                return ResourceManager.GetString("Traded_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traded Open 的本地化字符串。
        /// </summary>
        internal static string Traded_Open {
            get {
                return ResourceManager.GetString("Traded_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradeDate 的本地化字符串。
        /// </summary>
        internal static string TradeDate {
            get {
                return ResourceManager.GetString("TradeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradeDetail 的本地化字符串。
        /// </summary>
        internal static string TradeDetail {
            get {
                return ResourceManager.GetString("TradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradedWindow 的本地化字符串。
        /// </summary>
        internal static string TradedWindow {
            get {
                return ResourceManager.GetString("TradedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradeID 的本地化字符串。
        /// </summary>
        internal static string TradeID {
            get {
                return ResourceManager.GetString("TradeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string TradePrice {
            get {
                return ResourceManager.GetString("TradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradeTime 的本地化字符串。
        /// </summary>
        internal static string TradeTime {
            get {
                return ResourceManager.GetString("TradeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        internal static string TradeVolume {
            get {
                return ResourceManager.GetString("TradeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TradingType 的本地化字符串。
        /// </summary>
        internal static string TradingType {
            get {
                return ResourceManager.GetString("TradingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateTime 的本地化字符串。
        /// </summary>
        internal static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseMargin 的本地化字符串。
        /// </summary>
        internal static string UseMargin {
            get {
                return ResourceManager.GetString("UseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserClient 的本地化字符串。
        /// </summary>
        internal static string UserClient {
            get {
                return ResourceManager.GetString("UserClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VolumeRemain 的本地化字符串。
        /// </summary>
        internal static string VolumeRemain {
            get {
                return ResourceManager.GetString("VolumeRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VolumeTraded 的本地化字符串。
        /// </summary>
        internal static string VolumeTraded {
            get {
                return ResourceManager.GetString("VolumeTraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YesterdayPosition 的本地化字符串。
        /// </summary>
        internal static string YdPosition {
            get {
                return ResourceManager.GetString("YdPosition", resourceCulture);
            }
        }
    }
}
